// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WebApp.DAL;
using WebApp.Infrastructure;

namespace WebApp.Migrations
{
    [DbContext(typeof(PetTrackingContext))]
    partial class PetTrackingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApp.DAL.Pet", b =>
                {
                    b.Property<string>("BeaconID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int>("Kind");

                    b.Property<string>("Name");

                    b.Property<int>("Status");

                    b.HasKey("BeaconID");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("WebApp.DAL.TrackingInfo", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("BatchID");

                    b.Property<string>("BeaconID");

                    b.Property<DateTime>("FrameEndTime");

                    b.Property<DateTime>("FrameStartTime");

                    b.Property<string>("GeoReversedAddress");

                    b.Property<string>("GpsCoordinates");

                    b.Property<int>("MaxProximityInFrame");

                    b.Property<DateTime>("MaxProximityTime");

                    b.Property<int>("MinProximityInFrame");

                    b.Property<int>("MinProxmityTime");

                    b.Property<int>("ProximityAtFrameEnd");

                    b.Property<int>("ProximityAtFrameStart");

                    b.HasKey("ID");

                    b.ToTable("TrackingInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
